### PR TITLE
Update NXDNHosts.txt

### PR DESCRIPTION
**Pull request by Merlinv3**
Update NXDNHosts.txt thank you very much for all the work these days

### CODE REVIEW

**Comment by g4klx** [comment]
You are adding seven reflectors with the same host and port, this does not seem correct. Please explain how this works?

**Comment by Merlinv3** [comment]
yes, and if you look at the list there are more with the same dns and port... this is why they are pointing to david's new PA7LIM system: http://nxdn.pa7lim.nl/
now all those old nxdn spotlights have been taken offline and are now pointing at david's system..
when you call one of the reflectors I have added in the hostfiles list, you show up in david's system in the corresponding TG....it is still in development and david is hard at work on the reflector...
but don't worry, there are more hostfiles before that are pointing to nxdn.pa7lim.nl and it works correctly there are no conflicts..
as people want to switch to this new system, we will have to change the hostfiles to point to the new one... I thank you for your patience in all these days of so many changes in the hostfiles

**Comment by g4klx** [comment]
The whole point of the reflector system was that each reflector would be an independent system, this gives two advantages:
1. Resilience, if one fails, the others do not.
2. Politics, people were not beholden to one network provider, like DMR.
I feel that this approach is the opposite of the principles that this system (like P25, D-Star, M17, and YSF) is based upon. I'll consider whether to let them in, or remove all references to the PA7LIM system. I have met PA7LIM and like him, but I don't like centralised systems.

**Comment by Merlinv3** [comment]
ok, I understand, but it is the people who write to join the system... I don't like centralized systems either and especially with many laws like bm... but this new system gives the opportunity that people can choose to join and also you can see all the traffic in the same board, without the need to go board to board ... that's why people are joining ... whatever decision I make, it will be correct, thanks again

**Pull request merged**
