### PR TITLE
Update NXDNHosts.txt

### PR DESCRIPTION
**Pull request by Guanchindeverin**

### CODE REVIEW

**Comment by g4klx** [comment]
Can you remove the line deletion that you've included in the PR please.

**Comment by Guanchindeverin** [comment]
Line deletion?? no idea

**Comment by g4klx** [comment]
You delete line 431, please reinstate it.

**Comment by Guanchindeverin** [comment]
Done!
Sorry. I have become a sorcerer without knowing the herbs.
73's

**Pull request merged**
