### PR TITLE
Update NXDNHosts.txt

### PR DESCRIPTION
**Pull request by matt949**
Add TG 65400 NXDN

### CODE REVIEW

**Comment by matt949** [comment]
It is a new NXDN reflector as part of XLX288. My P25 TG is also 65400. If another TG # other than 65400 needs to be assigned for NXDN, that's OK. I just don't want to have to keep putting it in manually. 

Host is xlx288.unusualperson.com which resolves to 172.112.239.190.

**Comment by g4klx** [comment]
But what is the reflector for? A particular group of people? A particular location? Please give more information.

**Comment by matt949** [comment]
It's for a few repeaters here in Southern California (Los Angeles) to interconnect. My call is N6OGM. The repeaters are MMDVM based.

**Comment by matt949** [comment]
Do I need to re-pull this with some changes or? I'm not sure if/what I've done wrong. I didn't have this problem with my P25 reflector addition. Thank you.

**Comment by g4klx** [comment]
Please provide more details on your hosts file entry and then all will be good.

**Comment by matt949** [comment]
OK I'll close this one out and open up a new one with that info. Thank you. Sorry to be a pest.

**Pull request closed without merging**
